### PR TITLE
Removing Meta class from Model definition

### PR DESCRIPTION
**Pull request by aminalaee**
As it was suggested in #4, I think it would be nice to remove the Meta class, at least from the documentation but it will still work if defined:

```python
class Movie(Model, db=db, collection="movies"):
    name: str
    year: int
```

Instead of:

```python
class Movie(mongox.Model):
    name: str
    year: int

    class Meta:
        collection = db.get_collection("movies")
```

We could also remove db and accept `Collection` instances, but I think this will be easier.

**Update**:
Ass suggested by @MAD-py we the `db` argument will be required and the `collection` will be `<class_name>s` if not provided.

### CODE REVIEW

**Comment by aminalaee** [comment]
@yezz123 @MAD-py @ischaojie Any feedback would be appreciated guys.

**Review by yezz123 — APPROVED** [review]
It's look good for me 👍🏻

**Review by MAD-py — COMMENTED** [review]
Hey,

The idea is very good but I think it would also be good to add some validations, because for example this works and it does not give error until you get to a query.

```py
class Movie(mongox.Model, db=db):
    name: str
    year: int
```

It would also be good to get the class name to use as a default value in the collection.

**Comment by aminalaee** [comment]
@MAD-py yeah that's my plan to add validation too.

But the automatic name is really good. I'll add it tomorrow. Thanks.

**Comment by aminalaee** [comment]
Also need to figure out a way for Index part.

Either we should add it like the db and collection or we will do like `collection.add_index()`.

**Comment by MAD-py** [comment]
I think it would be better to have `Movie.set_index()` and then use `Movie.create_indexes()`.

What do you think?

**Comment by kuutsav** [comment]
> @MAD-py yeah that's my plan to add validation too.
> 
> But the automatic name is really good. I'll add it tomorrow. Thanks.

I feel the validation should be optional. If the user is confident then they should not have to validate their query every time.

**Comment by aminalaee** [comment]
> > @MAD-py yeah that's my plan to add validation too.
> > But the automatic name is really good. I'll add it tomorrow. Thanks.
> 
> I feel the validation should be optional. If the user is confident then they should not have to validate their query every time.

It's not about query validation. It's about validating the db instance. And that the collection name is provided.

**Comment by kuutsav** [comment]
> > > @MAD-py yeah that's my plan to add validation too.
> > > But the automatic name is really good. I'll add it tomorrow. Thanks.
> > 
> > 
> > I feel the validation should be optional. If the user is confident then they should not have to validate their query every time.
> 
> It's not about query validation. It's about validating the db instance. And that the collection name is provided.

Sorry i missed the context. Sounds good.

**Pull request merged**
