### PR TITLE
Version 0.1.0

### PR DESCRIPTION
**Pull request by aminalaee**
### Added

* `get_or_create` method by @MAD-py in https://github.com/aminalaee/mongox/pull/23
* Avoid `Meta` class from Model definition by @aminalaee in https://github.com/aminalaee/mongox/pull/25
* Fix bulk update return by @MAD-py in https://github.com/aminalaee/mongox/pull/29

### Internal

* Fixed autouse fixtures by @kuutsav in https://github.com/aminalaee/mongox/pull/26

## New Contributors
* @MAD-py made their first contribution in https://github.com/aminalaee/mongox/pull/21
* @kuutsav made their first contribution in https://github.com/aminalaee/mongox/pull/26

**Full Changelog**: https://github.com/aminalaee/mongox/compare/0.0.3...0.1.0

### CODE REVIEW

**Comment by MAD-py** [comment]
Hey,

Wouldn't it be better to wait for this #25 ?

**Comment by aminalaee** [comment]
Oh yeah, sorry I forgot to update the description. I'm waiting for #25 and #27

**Comment by aminalaee** [comment]
I think we can do the release now and add the additional features later.

**Review by MAD-py — APPROVED** [review]
Ok, I agree with you, we can do it this way.

**Pull request merged**
